# Generated by Django 3.1.5 on 2021-04-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_userquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='mobileNumber',
            field=models.IntegerField(),
        ),
    ]
